### ISSUE TITLE
Errors out with this pdf

### ISSUE THREAD

**Issue by vprelovac** [metebalci/pdftitle#20]
http://www.qwantz.com/fanart/superman.pdf

pdfminer.pdffont.PDFUnicodeNotDefined: (None, 28)

**Comment by metebalci** [comment]
This error is because the supplied pdf contains an undefined unicode (in this case at least the fi glyph in the title). It can be overcome by using `--replace-missing-char` argument (this problem can be seen in verbose mode). For example:

```
$ pdftitle --replace-missing-char ' ' -p superman.pdf 
AUni edtheoryofSuperman’sPowers
```

However, there are problems with spaces as they are not regular character spaces but instead each word is in an individual block. Unfortunately, I dont plan to implement anything to solve this at the moment. I mark this as an enhancement but closing the issue.
