### ISSUE TITLE
Tests and continuous integration (CI) by travis seems to be broken

### ISSUE THREAD

**Issue by cknoll** [metebalci/pdftitle#28]
The link behind the test-badge (i.e. https://www.travis-ci.com/metebalci/pdftitle) leads to a 404 error. I think this is because travis ceased its free service some time ago.

Also, when I run the tests locally on my machine I they fail due to pylint returning a nonzero exitcode.
 However, the actual tests of the functionality work just fine.

I wanted to propose https://cloud.drone.io. However, unexpectedly I could not start a build process for the forked repo. Maybe I find the problem or an alternative solution. Meanwhile I would propose to remove the invalid badge from the `README.md` file.

**Comment by metebalci** [comment]
Thanks for raising this, I totally missed the news regarding travis. I think there was also an update on pylint which was causing the pylint error. I have fixed it (disabled the pylint error for the moment) and added circleci config and updated the badge. This issue is fixed with 5ebc1a0ec3f347e5a257485bc6ce43a9f12798ba, I did not update the program version.
