### ISSUE TITLE
Empty title detected for some document

### ISSUE THREAD

**Issue by user202729** [metebalci/pdftitle#45]
Example https://eprint.iacr.org/2008/230

```bash
[]$ pdftitle -p 2008-230.pdf

[]$ echo $?
0
[]$ 
```

**Comment by metebalci** [comment]
The reason is there is an empty character with a larger font than the title. Since the title has the second large font, it can be found like this: 
```
$ pdftitle -a eliot --eliot-tfs 1 -p 230.pdf
A New Collision Differential For MD5 With Its Full Differential Path
```

Note to myself, there are two improvements needed: 

1. If a block is empty or contains only spaces (and tabs etc.), ignore this block. This will for example solve the issue for this pdf.
2. Blocks (and font sizes) are not visible to the user, it is hard to use eliot algorithm like this. Add a new command line option to list the blocks (in a human friendly way) to inform the user (this is not primarily for debugging).
